[tool.poetry]
name = "class-elective-advisor"
version = "0.1.0"
description = ""
authors = ["Matthew Dobley <mkmshopping@sbcglobal.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
